library(methods)
library(ggplot2)
data_time <- read.csv("Timing_profile.csv")
data_column1 <- data.frame(func=data_time$Func1,time=data_time$time1)
data_column2 <- data.frame(func=data_time$Func2,time=data_time$time2)
final_data <- rbind(data_column1,data_column2)
final_data <- unique(final_data)
p0 <- ggplot(data=final_data, aes(x=func,y=time,fill=func))
p0 + geom_bar(stat="identity")
